# GitHub リポジトリ設定
# このファイルは、GitHub Settingsアプリと組み合わせて使用することで
# リポジトリの設定を自動化できます

repository:
  # リポジトリの基本設定
  name: kabukan_v2
  description: "AWS Lambda ベースの株式分析システム - 自動的な株価分析とSlack通知機能"
  homepage: https://github.com/username/kabukan_v2
  topics:
    - aws-lambda
    - stock-analysis
    - python
    - serverless
    - eventbridge
    - slack-integration
    - google-sheets
    - gemini-ai
    - automation

  # リポジトリの可視性とアクセス設定
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true

  # デフォルトブランチ
  default_branch: main

  # 機能の有効化
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

  # セキュリティ設定
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# ブランチ保護設定
branches:
  - name: main
    protection:
      # レビュー必須設定
      required_status_checks:
        strict: true
        contexts:
          - "CI Pipeline / lint-and-format"
          - "CI Pipeline / unit-tests"
          - "CI Pipeline / integration-tests"
          - "Security Scan / dependency-check"
          - "Security Scan / code-security"

      # プルリクエストレビュー必須
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true

      # プッシュ制限
      enforce_admins: false
      restrictions:
        users: []
        teams: ["stock-analysis-team"]
        apps: ["github-actions"]

      # その他のルール
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI Pipeline / lint-and-format"
          - "CI Pipeline / unit-tests"

      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true

      enforce_admins: false
      allow_force_pushes: false
      allow_deletions: false

# ラベル設定
labels:
  # タイプ別ラベル
  - name: "type: bug"
    color: "d73a4a"
    description: "バグレポート"

  - name: "type: feature"
    color: "0075ca"
    description: "新機能の追加"

  - name: "type: enhancement"
    color: "a2eeef"
    description: "既存機能の改善"

  - name: "type: documentation"
    color: "0052cc"
    description: "ドキュメントの更新"

  - name: "type: refactoring"
    color: "5319e7"
    description: "リファクタリング"

  # 優先度ラベル
  - name: "priority: critical"
    color: "b60205"
    description: "緊急対応が必要"

  - name: "priority: high"
    color: "d93f0b"
    description: "高優先度"

  - name: "priority: medium"
    color: "fbca04"
    description: "中優先度"

  - name: "priority: low"
    color: "0e8a16"
    description: "低優先度"

  # 状態ラベル
  - name: "status: needs-triage"
    color: "ededed"
    description: "トリアージが必要"

  - name: "status: in-progress"
    color: "fbca04"
    description: "作業中"

  - name: "status: blocked"
    color: "d93f0b"
    description: "ブロックされている"

  - name: "status: ready-for-review"
    color: "0075ca"
    description: "レビュー準備完了"

  # 領域別ラベル
  - name: "area: infrastructure"
    color: "1d76db"
    description: "インフラストラクチャ関連"

  - name: "area: security"
    color: "b60205"
    description: "セキュリティ関連"

  - name: "area: ci/cd"
    color: "0052cc"
    description: "CI/CDパイプライン関連"

  - name: "area: lambda"
    color: "ff9500"
    description: "Lambda関数関連"

  - name: "area: eventbridge"
    color: "ff6600"
    description: "EventBridge関連"

  - name: "area: api"
    color: "1f8c00"
    description: "API関連（Google Sheets, Gemini, Slack）"

  - name: "area: testing"
    color: "006b75"
    description: "テスト関連"

  # 特別なラベル
  - name: "dependencies"
    color: "0366d6"
    description: "依存関係の更新"

  - name: "breaking-change"
    color: "b60205"
    description: "破壊的変更を含む"

  - name: "good first issue"
    color: "7057ff"
    description: "初心者向けの課題"

  - name: "help wanted"
    color: "008672"
    description: "コミュニティからの支援を求む"

# マイルストーン設定
milestones:
  - title: "v1.0.0 - Initial Release"
    description: "株式分析システムの初期リリース"
    state: open

  - title: "v1.1.0 - Performance Improvements"
    description: "パフォーマンス改善とモニタリング強化"
    state: open

  - title: "v1.2.0 - Advanced Features"
    description: "高度な分析機能の追加"
    state: open

# 環境設定
environments:
  - name: development
    wait_timer: 0
    reviewers: []
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true

  - name: staging
    wait_timer: 0
    reviewers:
      - stock-analysis-team
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

  - name: production
    wait_timer: 30  # 30分の待機時間
    reviewers:
      - stock-analysis-team
      - production-team
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

  - name: production-approval
    wait_timer: 0
    reviewers:
      - production-team
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false